// This file holds all text generated by JavaScript.  To translate the
// JavaScript, simply make a copy of this file and rename it to the
// corresponding language for the PHP translation, e.g. pt_BR.js for Brazilian
// Portugese.  Simply translate the strings into your language, leaving the %1$s
// symbols intact.
// Please note that you should use UTF-8 as the character encoding for this
// file.  As you probably know, bad things happen when encodings get mixed.

var strings = {

	entry_deleteConfirm: "Really delete %1$s?",
	
	editor_addImageDesc: "Add image %1$s.\nEnter image description:",
	editor_addLinkDesc: "Add link to %1$s.\nEnter link text:",
	
	editor_submitWithFiles: "Save draft before preview?\nIf you do not, your file uploads will be lost.",
    
    editor_leavePrompt: "You have unsaved changes.  Do you really want to leave the page?",
    editor_removeLink: "Remove file"
	
};
